services:
  # A Docker web service
  - type: web
    name: yt-scraper
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: pip install -r requirements.txt
    preDeployCommand: npx prisma migrate deploy
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT